# Generated by Django 3.0.2 on 2020-02-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_upload',
            name='num',
            field=models.TextField(default=3),
        ),
    ]
