# Generated by Django 3.0.2 on 2020-02-02 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_file_upload_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file_upload',
            name='num',
        ),
    ]
